README.md
=> Problem: no read me file

package-lock.json, package.json, src/components/CoinFooter.js, src/components/CoinHeader.js, src/components/CoinsStats.js, src/components/CommentCard.js, src/components/NewsCard.js, src/components/PriceCard.js, src/components/SummaryCard.js, src/screens/HomeScreen.js
Solution: Modify the overview UI
=> Problem: overview UI is not good enough

src/components/CommentCard.js, src/components/PriceCard.js
=>  Problem: overview UI incomplete

src/components/CoinOverview.js, src/components/CoinsStats.js
Solution: Change button into Tab
=> Problem: Button is not good for tab

package-lock.json, package.json, src/components/CoinsStats.js
=> Problem: IOS header overlap with status bar

src/components/Coin_Stats/CoinComment.js, src/components/Coin_Stats/CoinNews.js, src/components/Coin_Stats/CoinOverview.js, src/components/Coin_Stats/CoinWall.js, src/components/Coin_Stats/CoinsStats.js, src/components/Coin_Stats/CommentCard.js, src/components/Coin_Stats/NewsCard.js, src/components/Coin_Stats/Overview/NewsCard.js, src/components/Coin_Stats/Overview/PriceCard.js, src/components/Coin_Stats/Overview/SummaryCard.js, src/components/Coin_Stats/Overview/TopCommentCard.js, src/screens/HomeScreen.js
Solution: add a comment and wall page & minor fix
=> Problem: Not comment and Wall

src/components/Coin_Stats/Overview/NewsCard.js, src/components/Coin_Stats/Overview/SummaryCard.js
Solution: fixed bugs in overview import
=> Problem: Bugs in import

src/components/Coin_Stats/Overview/PriceCard.js
Solution: fix the import bug in PriceCard.js
=> Problem: Bug when importing react

src/components/Coin_Stats/CoinComment.js
=> Problem : ios send button disappear

src/components/Coin_Stats/CoinFooter.js
solution: use close icon instead of unheart.
=> problem: dislike is not brutal enough

src/screens/HomeScreen.js
Solution: change tab to scollable tab
=> Problem: no place to put app info and login panel

src/components/Coin_Stats/CoinSearch.js, src/screens/HomeScreen.js
Solution: Hide search bar when it is not needed, add a Search page
=>  Problem: like/dislike button appear on unneeded page and no search page

package-lock.json, package.json, src/components/Coin_Stats/CoinHeader.js, src/components/Coin_Stats/Overview/PriceCard.js, src/screens/HomeScreen.js
Solution: add a new header with action list, move some pages into action list
=> Problem: header icons are too crowded

src/components/Coin_Stats/CoinHeader.js, src/screens/HomeScreen.js
=> Problem: IOS status bar marginTop is too big

src/components/Coin_Stats/CoinFooter.js
Solution: change button color and icon
=> Problem: hard to distinglish like/dislike

src/components/Coin_Stats/CoinHeader.js, src/components/Login/LoginHeader.js, src/navigation/AppNavigator.js, src/navigation/AuthStackNavigator.js, src/navigation/MainStackNavigator.js, src/screens/AuthStack/LoginScreen.js
Solution: add a Auth stack navigator and create a login screen
=> Problem: No login/Sign up route

src/components/Login/LoginHeader.js, src/navigation/AuthStackNavigator.js, src/screens/AuthStack/ForgotScreen.js, src/screens/AuthStack/LoginScreen.js, src/screens/AuthStack/SignUpScreen.js
Solution: Add Signup and ForgotPassword Screen to Authstack
=> Problem: Authstack doesnt has a SignUp and ForgotPassword Screen

src/components/Coin_Stats/CoinOverview.js, src/components/Coin_Stats/CoinPrice.js, src/components/Coin_Stats/CommentCard.js, src/components/Coin_Stats/NewsCard.js, src/components/Coin_Stats/Overview/PriceCard.js, src/screens/HomeScreen.js
Solution: Set marginLeft to 0 and paddingLeft to 15
=> Problem: unneeded margin of Listitem on list

package-lock.json, package.json, src/components/AndroidBack.js, src/screens/AboutScreen.js, src/screens/AuthStack/ForgotScreen.js, src/screens/AuthStack/LoginScreen.js, src/screens/AuthStack/SignUpScreen.js
Solution: Add an android back button handler
=> Problem: Android Hardware Back button is not handled

README.md
Solution: Add an annotation in README
=> Problem: development mode issue

app.json, src/components/Coin_Stats/CoinNews.js, src/components/Coin_Stats/CoinWall.js, src/components/Coin_Stats/NewsCard.js, src/screens/AboutScreen.js
Solution: Add a link to github + some minor icon,UI changes
=> Problem: no link to github

src/components/AppStyle.js, src/components/Coin_Stats/CoinNews.js, src/components/Coin_Stats/CoinPrice.js, src/components/Coin_Stats/Overview/NewsCard.js, src/components/Coin_Stats/Overview/PriceCard.js, src/components/Coin_Stats/Overview/SummaryCard.js
=> Problem: No Price Page

src/components/Coin_Stats/CoinHeader.js, src/components/Coin_Stats/CoinPrice.js, src/components/Header.js, src/navigation/MainStackNavigator.js, src/screens/AuthStack/ForgotScreen.js, src/screens/AuthStack/LoginScreen.js, src/screens/AuthStack/SignUpScreen.js, src/screens/HomeScreen.js, src/screens/SearchScreen.js, src/screens/WallScreen.js
=> Problem: UI not good enough

App.js, package-lock.json, package.json, redux/app-redux.js, src/screens/AuthStack/LoginScreen.js
Solution: Added basic redux action-reducer-store & react-native meteor implementation
=> Problem: Not implement with the meteor backend yet

App.js, src/redux/app-redux.js, src/screens/AuthStack/LoginScreen.js
=> Problem: redux not implemeted porperly

src/screens/AuthStack/LoginScreen.js
Solution: modify profile screen
=> Problem: Profile screen broke

App.js, package-lock.json, package.json, src/screens/AuthStack/ForgotScreen.js, src/screens/AuthStack/LoginScreen.js, src/screens/AuthStack/SignUpScreen.js
Solution: implement Signup & Forgot password
=> Problem: SignUp & Forgot password is not implemented

src/screens/AuthStack/LoginScreen.js
=> Problem: login screen using alert

src/components/Profile.js, src/redux/app-redux.js, src/screens/AuthStack/LoginScreen.js
Solution: subscribe to the Meteor database
=> Problem: Profile not showing profile details

src/components/AllCoins.js, src/components/AndroidBack.js, src/components/Header.js, src/components/Profile.js, src/screens/HomeScreen.js
Solution: Subscribe to the correct currencies collection
=>  Problem: Meteor scribe to the wrong currencies.

src/components/AllCoins.js, src/components/Profile.js, src/navigation/MainStackNavigator.js, src/screens/CoinFeatures.js, src/screens/CoinSummary.js, src/screens/CoinrRedFlag.js, src/screens/HomeScreen.js, src/screens/SearchScreen.js
Solution: add coin list on search page and getting data from backend
=>  Problem: not showing coin list

src/components/AllCoins.js, src/components/Header.js, src/screens/CoinFeatures.js, src/screens/CoinSummary.js, src/screens/CoinrRedFlag.js, src/screens/SearchScreen.js
Solution: add a search filter on Search Page
=> Problem: no search function in search page

src/components/AllCoins.js
Solution: remove the redundant code
=> Problem: Redundant code in search page

src/redux/app-redux.js, src/screens/HomeScreen.js
Solution: implement redux and meteor together to get data
=> Problem: Homepage is not showing server side data

src/components/Coin_Stats/CoinFooter.js, src/components/Coin_Stats/CoinOverview.js, src/components/Coin_Stats/Overview/PriceCard.js, src/components/Coin_Stats/Overview/SummaryCard.js, src/redux/app-redux.js, src/screens/HomeScreen.js
Solution: implement redux and meteor to get data
=>  Problem: Price card and Summary card show static data

src/components/Coin_Stats/CoinFooter.js, src/components/Coin_Stats/CoinOverview.js, src/components/Coin_Stats/Overview/SummaryCard.js, src/components/Coin_Stats/Overview/TopCommentCard.js, src/screens/HomeScreen.js
Solution: implement redux and meteor to get data & add navigation to screen
=>  Problem: Features card is static & Summary card not navigating 

src/components/AllCoins.js, src/components/Coin_Stats/Overview/TopCommentCard.js, src/screens/CoinFeatures.js, src/screens/CoinSummary.js
Solution: Add navigation &  modify the function to the app
=>  Problem: Features not navigating & Seach Page Items are are not changing the page 

src/components/AllCoins.js, src/components/Coin_Stats/Overview/PriceCard.js, src/components/Coin_Stats/Overview/TopCommentCard.js
=>  Problem: overview not showing redflag

package-lock.json, src/components/Coin_Stats/CoinComment.js, src/components/Coin_Stats/CommentCard.js, src/components/Coin_Stats/Overview/TopCommentCard.js
Solution: add a screen to show red flags & get data from server and sort it by created date
=>  Problem: redflag card is not navigating & comment screen is showing static data 

src/components/Coin_Stats/CoinComment.js, src/components/Coin_Stats/CommentCard.js
=> Problem: comments screen vote number incorrect

package-lock.json, package.json, src/components/Coin_Stats/CoinComment.js, src/components/Coin_Stats/CommentCard.js, src/components/Profile.js, src/redux/app-redux.js, src/screens/AuthStack/LoginScreen.js
Solution: add vote function & Fixed by Using Meteor.user instaead of redux
=>  Problem: use cannot vote &Not showing login profile after restart

src/components/Coin_Stats/CoinComment.js, src/components/Coin_Stats/CommentCard.js
=> Problem: comment page UI not good

src/components/Coin_Stats/CoinComment.js
Solution: Add a Title to show the name
=> Problem: comment section not show the coin's name

src/components/Coin_Stats/CoinComment.js, src/components/Coin_Stats/CoinOverview.js, src/components/Coin_Stats/Overview/TopCommentCard.js, src/screens/HomeScreen.js
Solution: navigate the tab instead of showing a stack screen
=> Problem: overview topcomment card not navigating the tabs

src/components/Coin_Stats/CoinComment.js
Solution: change the sorting from createdAt to rating
=> Problem: comment order is not sorted by rating

package-lock.json, src/screens/CoinSummary.js
Solution: add a vote function with meteor call
=> Problem: cant vote on summary

src/screens/CoinSummary.js
=> Problem: summary are not sorted by rating

src/components/Coin_Stats/CoinComment.js, src/components/Coin_Stats/CoinPrice.js, src/components/Coin_Stats/Overview/SummaryCard.js
=> Problem: price UI not good

package-lock.json, package.json, src/components/Coin_Stats/CoinPrice.js
Solution: add a Progress graph to show the fundamental metrics
=> Problem: Price screen is not showing the graph

package-lock.json, src/components/Coin_Stats/CoinPrice.js
=> Problem: metrix color doesnt looks good

App.js, src/components/AllCoins.js, src/components/Coin_Stats/CoinComment.js, src/components/Coin_Stats/CoinFooter.js, src/navigation/MainStackNavigator.js, src/screens/LikedCoinScreen.js, src/screens/SearchScreen.js
Solution: implement Liked Coin
=>  Problem: Liked Coin not implemented 

src/components/Profile.js
=> Problem: Error when user log out

src/components/Coin_Stats/CoinFooter.js
Solution: stop sending request to server when it is loading
=> Problem: User should not be able to like/dislike coins when loading

src/components/Coin_Stats/CoinFooter.js
Solution: Show next coin button when user is not logged in
=> Problem: Like/Dislike appears when not logged in

src/screens/LikedCoinScreen.js
Solution: change the search by using userId
=> Problem: user liked coin search using _id

src/components/Coin_Stats/CoinPrice.js, src/screens/CoinSummary.js
Solution: Change the title from slug to name
=> Problem: Summary page is showing slug instead of Name

App.js, src/components/Coin_Stats/CoinComment.js, src/components/Coin_Stats/CoinHeader.js, src/components/Header.js, src/components/Profile.js
Solution: Show Profile after Login & add a tab to show wallet and profile
=>  Problem: ActionSheet showing Login/Sign Up after login & profile is not good 

src/components/Profile.js
Solution: Added an edit function to profile page
=> Problem: Users are not able to edit profile

src/components/Coin_Stats/Overview/PriceCard.js, src/components/Coin_Stats/Overview/TopCommentCard.js
=> Problem: UI wordings needs to be change

src/components/Coin_Stats/CoinComment.js, src/components/Coin_Stats/Overview/TopCommentCard.js
Solution: remove buttons && Call the wrapped backend function(Meteor.call('addNewFeatureMobile')
=> Problem: Like/Dislike button should be removed in overview && Cannot add feature

src/components/Coin_Stats/CoinComment.js
Solution: add redflag by calling(Meteor.call(newRedFlagMethod)
=> Problem: User Cannt add redflag

src/components/Coin_Stats/CoinComment.js
Solution: hide user input when user isn't logged in, show alert box to let user to choose stance after typing the comment
=> Problem: user add comment flow is not good enough

package-lock.json, package.json, src/components/Coin_Stats/CoinComment.js, src/components/Coin_Stats/CoinPrice.js, src/components/Coin_Stats/Overview/PriceCard.js, src/screens/HomeScreen.js
Solution: Add bcp in price page
=> Problem: Price page is not showing BCP

src/components/Coin_Stats/CoinComment.js, src/components/Coin_Stats/CoinFooter.js, src/screens/HomeScreen.js
Solution: change to showing alert instead of hiding the functions
=> Problem: Not showing alert when user is not logged in

src/components/Coin_Stats/CoinComment.js
Solution: Clear the text after a successful submition
=> Problem: Text is not clear after submitting comment

src/components/Coin_Stats/CoinFooter.js, src/components/Coin_Stats/CoinHeader.js
Solution: add a tooltip with asyncstorage to remind user when first like occur
=> Problem: No reminder when user first liked the coin

src/components/Coin_Stats/CoinFooter.js, src/components/Coin_Stats/CoinPrice.js
Solution: close the tooltip box when user click on the child object
=> Problem: tooltip is not closing when click on child object
